"""
Alerts API Endpoints
SIH Problem Statement: SIH26062
"""
from typing import Dict, Any, Optional
from fastapi import APIRouter, HTTPException, Query, Depends
from pydantic import BaseModel
from app.services.simulation_service import simulation_service
from app.services.audit_service import audit_service
from app.schemas.alerts import AlertListResponse, AlertModel
from app.api.v1.endpoints.auth import require_permission, UserProfile

router = APIRouter()

ALERT_OVERRIDES: Dict[str, Dict[str, Any]] = {}


class UpdateAlertRequest(BaseModel):
    status: str = "ACKNOWLEDGED"  # ACKNOWLEDGED, IN_PROGRESS, RESOLVED
    operator: Optional[str] = None
    notes: Optional[str] = None


@router.get("", response_model=AlertListResponse)
def get_alerts(scenario_id: int = Query(1, ge=1, le=5, description="Scenario ID (1-5)")):
    """
    Get system alerts generated by deterministic telemetry conditions.
    """
    try:
        alerts_data = simulation_service.get_alerts(scenario_id)
        
        merged_alerts = []
        for a in alerts_data:
            a_copy = dict(a)
            a_id = a.get("id")
            if a_id and a_id in ALERT_OVERRIDES:
                a_copy.update(ALERT_OVERRIDES[a_id])
            merged_alerts.append(AlertModel(**a_copy))

        crit_count = sum(1 for a in merged_alerts if a.severity == "CRITICAL")
        warn_count = sum(1 for a in merged_alerts if a.severity == "WARNING")

        return AlertListResponse(
            scenario_id=scenario_id,
            total_alerts=len(merged_alerts),
            critical_alerts=crit_count,
            warning_alerts=warn_count,
            alerts=merged_alerts
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch alerts: {str(e)}")


@router.post("/{alert_id}/acknowledge")
def acknowledge_alert(
    alert_id: str,
    req: UpdateAlertRequest,
    current_user: UserProfile = Depends(require_permission("ACKNOWLEDGE_ALERTS"))
):
    """
    Operator action: Acknowledge or transition alert status.
    Protected by RBAC: requires ACKNOWLEDGE_ALERTS permission (Commander, Safety, Logistics, Field Operator, Admin).
    """
    valid_statuses = ["ACKNOWLEDGED", "IN_PROGRESS", "RESOLVED"]
    st_val = req.status.upper() if req.status.upper() in valid_statuses else "ACKNOWLEDGED"

    ALERT_OVERRIDES[alert_id] = {
        "status": st_val
    }

    operator_name = req.operator or current_user.full_name

    audit_service.log_action(
        operator=operator_name,
        role=current_user.role,
        action=f"ALERT_{st_val}",
        entity_type="ALERT",
        entity_id=alert_id,
        details={"status": st_val, "notes": req.notes}
    )

    return {
        "status": "success",
        "alert_id": alert_id,
        "alert_status": st_val,
        "message": f"Alert {alert_id} marked as {st_val}"
    }
